# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3501f1834c277fcb1714b33121fb662ca7cf12de1ab8753557a5e27ed6050f924429c658f7ef5e00852ef63e9b0a0cfb1698d71be35823e0a60d346ab5c41410

test:
  secret_key_base: 6055a6204841000f1cbb70a724999d6f3e18e2b26a4adbef931230a9e883c843a4761a2509ede2fcda16c1eaf21ad942a2fe3489265a9da99a1efc85e0ee99d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
